# model wiht XAI

- input을 3개 policy모두 동일(국면 + 5개 자산 월별 모든 정보)
- policy별 차이는 input을 해석/조정하는 방식(가중치, 제약, 목적함수)
- SHAP는 모든 정책에 대해 Kernel SHAP(동일 방법)
- 최종 출력은
  - 사용자 성향에 따른 포트폴리오 비중
  - 국면
  - SHAP 해석
  - 반대 성향의 포트폴리오 함께 제시

In [3]:
import json
import numpy as np
import pandas as pd
from dataclasses import dataclass
from sqlalchemy import text, create_engine
import shap

In [4]:
# sql 연결확인

ENGINE = create_engine(
    "mysql+pymysql://root:Jinyoung9806!@127.0.0.1:3306/robo?charset=utf8mb4",
    pool_pre_ping=True,
)

with ENGINE.connect() as conn:
    print(conn.execute(text("select 1")).fetchall())

[(1,)]

## MVP용 고정 설정
asset, profile, regime 고정 설정하고, 공통입력 설정

onehot 인코딩, float화, nan to zero 시행

각 테이블 별 공통 존재하는 월 데이터만 사용

In [43]:
# =========================
# A) 고정 설정 (MVP)
# =========================
ASSETS = ["CASH_BIL", "GLB_EQ_VTI", "KR_EQ_EWY", "GOLD_GLD", "LT_BOND_TLT"]
EQUITY_ASSETS = ["GLB_EQ_VTI", "KR_EQ_EWY"]
PROFILES = ["CONSERVATIVE", "AGGRESSIVE"]

# regime_monthly에서 쓰는 4개 국면(이미 만들어졌다고 가정)
REGIMES = ["RISK_ON", "RISK_ON_VOL", "DEFENSIVE", "RISK_OFF"]

# 공통 입력 X: (regime one-hot + profile one-hot + 자산별 피처)
# 자산별 피처는 "가능한 모든 정보"로 확장 가능 (여기서는 ret/vol/dd 중심)
ASSET_FEATURES = ["ret_1m", "ret_3m", "ret_12m", "vol_3m", "dd_6m", "dd_12m"]

def one_hot(value: str, categories: list[str]) -> np.ndarray:
    return np.array([1.0 if value == c else 0.0 for c in categories], dtype=float)

def safe_float(x, default=np.nan):
    try:
        if x is None:
            return float(default)
        if isinstance(x, float) and np.isnan(x):
            return float(default)
        return float(x)
    except Exception:
        return float(default)

def zfill_nan_to_zero(x: np.ndarray) -> np.ndarray:
    # Kernel SHAP/최적화 안정화를 위해 nan은 0으로 (입력공간 안정)
    x = x.copy()
    x[~np.isfinite(x)] = 0.0
    return x

def feature_names() -> list[str]:
    names = []
    names += [f"regime__{r}" for r in REGIMES]
    names += [f"profile__{p}" for p in PROFILES]
    for a in ASSETS:
        for f in ASSET_FEATURES:
            names.append(f"{a}__{f}")
    return names

def get_common_eoms(engine, min_assets=5) -> list[pd.Timestamp]:
    """
    regime_monthly와 feat_asset_monthly(ASSETS 모두)에서
    공통으로 존재하는 eom만 반환.
    """
    q = """
    with feat_ok as (
      select eom
      from feat_asset_monthly
      where asset_id in :assets
      group by eom
      having count(distinct asset_id) = :n_assets
    )
    select r.eom
    from regime_monthly r
    join feat_ok f on r.eom = f.eom
    order by r.eom
    """
    with engine.connect() as conn:
        df = pd.read_sql(text(q), conn, params={"assets": tuple(ASSETS), "n_assets": int(min_assets)})
    return pd.to_datetime(df["eom"]).tolist()

## 데이터 로더

eom 기준 regime과 자산별 feature 읽어오고 공통 입력 벡터로 만들기

In [44]:
# =========================
# B) 데이터 로더 (regime_monthly + feat_asset_monthly)
# =========================
def load_state(engine, eom: pd.Timestamp) -> dict:
    """
    특정 월말(eom) 기준으로:
    - regime_code (regime_monthly)
    - 자산별 피처 (feat_asset_monthly)
    를 읽어 state(dict)로 반환
    """
    q_reg = "select eom, regime_code from regime_monthly where eom = :eom"
    with engine.connect() as conn:
        reg = pd.read_sql(text(q_reg), conn, params={"eom": eom.date()})
    if reg.empty:
        raise RuntimeError(f"regime_monthly missing: {eom.date()}")
    regime = reg.loc[0, "regime_code"]

    # feat_asset_monthly에 ret/vol/dd가 있어야 함 (너가 ETL에서 만들었음)
    cols = ", ".join(ASSET_FEATURES)
    q_feat = f"""
    select asset_id, {cols}
    from feat_asset_monthly
    where eom = :eom and asset_id in :assets
    """
    with engine.connect() as conn:
        feat = pd.read_sql(text(q_feat), conn, params={"eom": eom.date(), "assets": tuple(ASSETS)})

    if set(ASSETS) - set(feat["asset_id"].tolist()):
        missing = list(set(ASSETS) - set(feat["asset_id"].tolist()))
        raise RuntimeError(f"feat_asset_monthly missing assets: {eom.date()} -> {missing}")

    feat = feat.set_index("asset_id").reindex(ASSETS)
    return {"eom": eom, "regime": regime, "feat": feat}

def state_to_X(state: dict, profile: str) -> np.ndarray:
    """
    state + profile -> 공통 입력 벡터 X (3정책 공통)
    """
    reg_oh = one_hot(state["regime"], REGIMES)
    prof_oh = one_hot(profile, PROFILES)

    vals = []
    feat = state["feat"]
    for a in ASSETS:
        for f in ASSET_FEATURES:
            vals.append(safe_float(feat.loc[a, f], default=np.nan))
    x = np.concatenate([reg_oh, prof_oh, np.array(vals, dtype=float)], axis=0)
    return zfill_nan_to_zero(x)

def build_X_matrix(engine, eoms: list[pd.Timestamp], profile: str) -> np.ndarray:
    """
    여러 eom에 대해 X 행렬 생성 (Kernel SHAP background/explain 용)
    """
    X = []
    for eom in eoms:
        st = load_state(engine, eom)
        X.append(state_to_X(st, profile))
    return np.vstack(X)

## 공분산/상관 추정

공통 유틸로 공분산/상관 추정함

In [45]:
# =========================
# C) 공통 유틸: 공분산/상관(설명/정책 공통으로 사용)
# =========================
def load_ret_wide(engine) -> pd.DataFrame:
    """
    공분산/상관 추정용: 월간 ret_1m wide
    """
    q = """
    select eom, asset_id, ret_1m
    from feat_asset_monthly
    where asset_id in :assets and ret_1m is not null
    order by eom, asset_id
    """
    with engine.connect() as conn:
        df = pd.read_sql(text(q), conn, params={"assets": tuple(ASSETS)})
    df["eom"] = pd.to_datetime(df["eom"])
    wide = df.pivot(index="eom", columns="asset_id", values="ret_1m").sort_index()
    return wide.reindex(columns=ASSETS)

def estimate_global_corr(ret_wide: pd.DataFrame, window_months: int = 60) -> np.ndarray:
    """
    최근 window_months 기반으로 '전역 상관'을 하나 뽑아둔다.
    - 정책 간 입력 정보 통일을 위해, Σ 구성에 동일 상관을 쓰는 게 깔끔함.
    """
    hist = ret_wide.tail(window_months).dropna(how="any")
    if len(hist) < 12:
        # 데이터가 부족하면 약한 상관으로 대체
        n = len(ASSETS)
        C = np.eye(n)
        C[C == 0] = 0.10
        return C
    C = np.corrcoef(hist.values.T)
    # 수치 안정화
    C = np.nan_to_num(C, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(C, 1.0)
    return C

def approx_cov_from_X(x: np.ndarray, corr: np.ndarray) -> np.ndarray:
    """
    ✅ DB에 있는 vol_3m만 사용해서 Σ 생성
    Σ = D(vol_3m) * corr * D(vol_3m)
    """
    offset = len(REGIMES) + len(PROFILES)
    f_idx = {f: i for i, f in enumerate(ASSET_FEATURES)}
    vol_i = f_idx["vol_3m"]
    block = len(ASSET_FEATURES)

    vols = []
    for ai in range(len(ASSETS)):
        base = offset + ai * block
        v = abs(x[base + vol_i])
        vols.append(max(v, 1e-6))
    vols = np.array(vols, dtype=float)

    D = np.diag(vols)
    Sigma = D @ corr @ D
    Sigma = Sigma + np.eye(len(ASSETS)) * 1e-8
    return Sigma

## mu 예측 모델

PRED_MVO에서 사용하기 위해 mu 추정해야.

입력은 자산별 feature 출력은 다음달 기대수익(mu)

In [46]:
# =========================
# D) μ 예측 모델 (PRED_MVO에서 사용)
# =========================
@dataclass
class MuModel:
    """
    단순화를 위해 sklearn 기반 모델을 사용.
    - 입력: (asset_id one-hot 없이) X에서 자산별 피처를 뽑아 구성
    - 출력: 다음달 기대수익(μ)
    """
    model: object
    asset_to_idx: dict

    def predict_mu(self, x: np.ndarray) -> np.ndarray:
        """
        x(1개 샘플) -> 자산별 μ(5개) 반환
        """
        # 자산별 피처를 모델 입력으로 재구성:
        # [regime_oh(4) + 자산별 ret/vol/dd (해당 자산 블록) + profile_oh(2)]
        # (정책 간 입력 통일을 위해 regime/profile/자산피처를 모두 사용)
        reg = x[:len(REGIMES)]
        prof = x[len(REGIMES):len(REGIMES)+len(PROFILES)]
        offset = len(REGIMES) + len(PROFILES)
        block = len(ASSET_FEATURES)

        X_rows = []
        for ai in range(len(ASSETS)):
            base = offset + ai * block
            asset_feats = x[base:base+block]
            row = np.concatenate([reg, prof, asset_feats], axis=0)
            X_rows.append(row)

        X_rows = np.vstack(X_rows)
        mu = self.model.predict(X_rows).astype(float)
        return mu

def train_mu_model(engine, ret_wide: pd.DataFrame) -> MuModel:
    """
    다음달 ret_1m_next를 타깃으로 간단 모델 학습.
    - 학습데이터 생성: (eom의 X) -> (eom+1의 ret_1m) 를 자산별로 매핑
    - 모델은 가볍게 HistGradientBoostingRegressor 사용(속도/안정)
    """
    from sklearn.ensemble import HistGradientBoostingRegressor

    # 공통 eom만 사용
    common_eoms = get_common_eoms(engine, min_assets=len(ASSETS))
    common_eoms = pd.to_datetime(common_eoms)

    # ret_wide도 공통 eom으로 정렬/필터
    ret_wide2 = ret_wide.loc[ret_wide.index.isin(common_eoms)].sort_index()

    # 다음달 타깃
    y_next = ret_wide2.shift(-1)

    X_train, y_train = [], []

    # 너무 오래 걸리면 여기서 샘플링 가능 (MVP)
    eoms = ret_wide2.index.tolist()
    for eom in eoms[:-1]:
        st = load_state(engine, eom)  # 이제 missing 안 남(교집합이니까)
        for profile in PROFILES:
            x = state_to_X(st, profile)

            reg = x[:len(REGIMES)]
            prof = x[len(REGIMES):len(REGIMES)+len(PROFILES)]
            offset = len(REGIMES) + len(PROFILES)
            block = len(ASSET_FEATURES)

            for ai, a in enumerate(ASSETS):
                base = offset + ai * block
                asset_feats = x[base:base+block]
                row = np.concatenate([reg, prof, asset_feats], axis=0)

                target = y_next.loc[eom, a]
                if pd.isna(target):
                    continue
                X_train.append(row)
                y_train.append(float(target))

    X_train = np.vstack(X_train) if len(X_train) else np.empty((0, len(REGIMES)+len(PROFILES)+len(ASSET_FEATURES)))
    y_train = np.array(y_train, dtype=float)

    if len(y_train) < 200:
        raise RuntimeError(f"Not enough training rows for mu model: {len(y_train)}")

    model = HistGradientBoostingRegressor(
        max_depth=4,
        learning_rate=0.05,
        max_iter=300,
        random_state=42
    )
    model.fit(X_train, y_train)

    return MuModel(model=model, asset_to_idx={a:i for i,a in enumerate(ASSETS)})

## 정책 3개(공통 입력을 모두 사용하고 정책별 조정 단계)

공통 PolicyParams는 사용자가 조정 가능(후에 데이터 기반으로 추정한다거나 하는 자동화 방법이 있는 방향으로)

각 policy별 조정은 코드 주석에 있음

In [47]:
@dataclass
class PolicyParams:
    # 공통
    corr: np.ndarray
    # CAR_RP
    car_rp_equity_cap_cons: float = 0.45
    car_rp_equity_cap_aggr: float = 0.75
    # MDD_GUARD
    mdd_equity_cap_cons: float = 0.20
    mdd_equity_cap_aggr: float = 0.35
    # PRED_MVO
    gamma_cons: float = 12.0
    gamma_aggr: float = 6.0
    w_max_each: float = 0.70
    mvo_equity_cap_cons: float = 0.60
    mvo_equity_cap_aggr: float = 0.90

def apply_equity_cap(w: pd.Series, cap: float) -> pd.Series:
    eq_sum = float(w.loc[EQUITY_ASSETS].sum())
    if eq_sum <= cap:
        return w
    w = w.copy()
    w.loc[EQUITY_ASSETS] *= (cap / eq_sum)
    non_eq = w.index.difference(EQUITY_ASSETS)
    w.loc[non_eq] *= (1.0 - float(w.loc[EQUITY_ASSETS].sum())) / float(w.loc[non_eq].sum())
    return w

def policy_compute_weights(policy: str, x: np.ndarray, params: PolicyParams, mu_model: MuModel | None) -> pd.Series:
    """
    공통 입력 x(동일 input)로부터 정책별 weight 산출.
    정책별 차이는:
    - 어떤 피처를 더 강하게 쓰는지(가중치/제약/목적)로만 반영
    """
    x = zfill_nan_to_zero(x)
    profile = PROFILES[int(np.argmax(x[len(REGIMES):len(REGIMES)+len(PROFILES)]))]

    # 공통: Σ는 모두 같은 규칙으로 구성 (입력의 vol + 전역 corr)
    Sigma = approx_cov_from_X(x, params.corr)

    # 공통: 입력에서 자산별 ret/vol/dd를 모두 꺼내서 "리스크/시그널 벡터" 구성
    offset = len(REGIMES) + len(PROFILES)
    block = len(ASSET_FEATURES)
    f_idx = {f:i for i,f in enumerate(ASSET_FEATURES)}

    ret3  = np.array([x[offset + ai*block + f_idx["ret_3m"]]  for ai in range(len(ASSETS))], dtype=float)
    ret12 = np.array([x[offset + ai*block + f_idx["ret_12m"]] for ai in range(len(ASSETS))], dtype=float)
    vol3  = np.array([abs(x[offset + ai*block + f_idx["vol_3m"]]) for ai in range(len(ASSETS))], dtype=float)
    dd6   = np.array([abs(x[offset + ai*block + f_idx["dd_6m"]])  for ai in range(len(ASSETS))], dtype=float)
    dd12  = np.array([abs(x[offset + ai*block + f_idx["dd_12m"]]) for ai in range(len(ASSETS))], dtype=float)

    # regime도 정책 조정에 사용 (동일 input을 정책별로 "조정"하는 방식)
    reg_oh = x[:len(REGIMES)]
    regime = REGIMES[int(np.argmax(reg_oh))]

    if policy == "CAR_RP":
        # CAR_RP: "리스크 균형"이 기본인데, 같은 입력을 더 많이 쓰기 위해
        # - 변동성(vol3)을 기본 risk로 사용
        # - dd(낙폭)가 큰 자산은 risk를 더 크게 본다(= 비중 더 낮아짐)
        # - ret(모멘텀)가 좋은 자산은 risk를 약간 완화(= 비중 소폭 상향)
        # - regime이 나쁠수록(DEFENSIVE/RISK_OFF) 주식 cap을 더 보수적으로
        risk = np.maximum(vol3, 1e-6) * (1.0 + 0.8*dd6 + 0.4*dd12)
        momentum = 0.5*ret3 + 0.5*ret12
        adj = np.exp(-0.6*momentum)  # 모멘텀이 좋으면 adj<1 -> risk 감소 -> 비중 증가
        eff_risk = risk * adj

        score = 1.0 / np.maximum(eff_risk, 1e-6)
        w = score / score.sum()
        w = pd.Series(w, index=ASSETS)

        if profile == "CONSERVATIVE":
            cap = params.car_rp_equity_cap_cons
        else:
            cap = params.car_rp_equity_cap_aggr

        # 국면에 따라 cap 조정(같은 입력을 정책에 반영)
        if regime == "RISK_OFF":
            cap *= 0.75
        elif regime == "DEFENSIVE":
            cap *= 0.85
        elif regime == "RISK_ON_VOL":
            cap *= 0.95

        w = apply_equity_cap(w, cap)
        w = w.clip(lower=0)
        w = w / w.sum()
        return w

    if policy == "MDD_GUARD":
        # MDD_GUARD: 목적은 낙폭 방어
        # - dd(낙폭)를 가장 강하게 사용
        # - vol이 크면 추가 패널티
        # - ret가 좋더라도 dd가 크면 방어 우선(= ret 영향은 약하게)
        # - regime이 나쁠수록 방어 강도 강화
        guard = (1.0 + 2.2*dd6 + 1.2*dd12) * (1.0 + 0.6*np.maximum(vol3, 0))
        # ret는 약하게만 반영 (좋으면 약간 완화)
        momentum = 0.7*ret3 + 0.3*ret12
        guard = guard * np.exp(-0.15*momentum)

        if regime in ["DEFENSIVE", "RISK_OFF"]:
            guard *= 1.10

        score = 1.0 / np.maximum(guard, 1e-6)
        w = score / score.sum()
        w = pd.Series(w, index=ASSETS)

        cap = params.mdd_equity_cap_cons if profile == "CONSERVATIVE" else params.mdd_equity_cap_aggr
        # 국면 나쁠수록 더 방어적으로
        if regime == "RISK_OFF":
            cap *= 0.80
        w = apply_equity_cap(w, cap)

        w = w.clip(lower=0)
        w = w / w.sum()
        return w

    if policy == "PRED_MVO":
        # PRED_MVO: 같은 입력을 모두 사용
        # - μ는 mu_model로 예측(= reg/profile/자산피처 모두 투입)
        # - Σ도 입력 vol + 공통 corr로 구성(= 동일 input 사용)
        if mu_model is None:
            raise RuntimeError("mu_model is required for PRED_MVO")
        mu = mu_model.predict_mu(x)  # (5,)

        gamma = params.gamma_cons if profile == "CONSERVATIVE" else params.gamma_aggr
        n = len(ASSETS)
        w_min = np.zeros(n)
        w_max = np.ones(n) * params.w_max_each

        eq_cap = params.mvo_equity_cap_cons if profile == "CONSERVATIVE" else params.mvo_equity_cap_aggr
        # 국면 나쁠수록 주식 cap 강화
        if regime == "RISK_OFF":
            eq_cap *= 0.85
        elif regime == "DEFENSIVE":
            eq_cap *= 0.92

        # SLSQP로 간단 MVO
        from scipy.optimize import minimize

        eq_idx = [ASSETS.index(a) for a in EQUITY_ASSETS]

        def obj(w):
            return 0.5 * gamma * float(w @ Sigma @ w) - float(mu @ w)

        cons = [{"type": "eq", "fun": lambda w: np.sum(w) - 1.0}]
        cons.append({"type": "ineq", "fun": lambda w, cap=eq_cap, idx=eq_idx: cap - np.sum(w[idx])})
        bounds = [(float(w_min[i]), float(w_max[i])) for i in range(n)]
        x0 = np.ones(n) / n

        res = minimize(obj, x0=x0, bounds=bounds, constraints=cons, method="SLSQP")
        if not res.success:
            # 실패하면 보수적으로 CAR_RP로 폴백(운영 안정성)
            # (같은 input 사용, 단 정책은 안전하게)
            return policy_compute_weights("CAR_RP", x, params, mu_model)

        w = np.clip(np.array(res.x, dtype=float), 0, 1)
        w = w / w.sum()
        return pd.Series(w, index=ASSETS)

    raise ValueError(f"Unknown policy: {policy}")

# Policy 선택

국면 + 성향 매핑으로 3policy 진행(이 또한 후에 더 가능)

In [48]:
# =========================
# F) policy 선택(국면+성향 매핑) - 3정책으로 단순화
# =========================
def choose_policy(regime: str, profile: str) -> str:
    """
    정책은 많을 필요 없다고 했으니, 단순 매핑:
    - 안정형 + 나쁜국면 => MDD_GUARD
    - 위험감수형 + 좋은국면 => PRED_MVO
    - 나머지 => CAR_RP
    """
    if profile == "CONSERVATIVE" and regime in ["DEFENSIVE", "RISK_OFF"]:
        return "MDD_GUARD"
    if profile == "AGGRESSIVE" and regime in ["RISK_ON", "RISK_ON_VOL"]:
        return "PRED_MVO"
    return "CAR_RP"

## DB 업서트

포트폴리오와 XAI 결과 upsert하는 단계(sql로)

In [49]:
def upsert_portfolio(engine, eom: pd.Timestamp, profile: str, policy: str, w: pd.Series, meta: dict | None = None):
    sql = """
    insert into portfolio_monthly (eom, profile, policy, asset_id, weight, meta_json)
    values (:eom, :profile, :policy, :asset_id, :weight, cast(:meta_json as json))
    on duplicate key update
      weight=values(weight),
      meta_json=values(meta_json)
    """
    rows = []
    meta_json = json.dumps(meta or {}, ensure_ascii=False)
    for asset_id, weight in w.items():
        rows.append({
            "eom": eom.date(),
            "profile": profile,
            "policy": policy,
            "asset_id": asset_id,
            "weight": float(weight),
            "meta_json": meta_json
        })
    with engine.begin() as conn:
        conn.execute(text(sql), rows)

def upsert_xai(engine, eom: pd.Timestamp, profile: str, policy: str, target: str,
               top_feats: list[dict], base_value: float | None):
    sql = """
    insert into xai_policy_monthly (eom, profile, policy, target, top_features_json, base_value)
    values (:eom, :profile, :policy, :target, cast(:top_json as json), :base_value)
    on duplicate key update
      top_features_json=values(top_features_json),
      base_value=values(base_value)
    """
    with engine.begin() as conn:
        conn.execute(text(sql), {
            "eom": eom.date(),
            "profile": profile,
            "policy": policy,
            "target": target,
            "top_json": json.dumps(top_feats, ensure_ascii=False),
            "base_value": base_value
        })

## Kernel SHAP

input은 우리가 사용한 feature들

output은 5개의 자산 비중인 포트폴리오

즉, 정해진 로직으로 포트폴리오 weight를 계산하고 그 결과를 출력값으로 사용

현재는 정해진 로직으로 포트폴리오 weight를 사용하지만, 이는 ML 등 데이터 기반 방안으로 충분히 변경이 가능

In [50]:
# =========================
# H) Kernel SHAP (모든 정책 공통)
# =========================
def policy_target_value(policy: str, x: np.ndarray, params: PolicyParams, mu_model: MuModel,
                        target: str = "equity_total") -> float:
    """
    Kernel SHAP이 설명할 scalar 출력.
    - target="equity_total": 주식비중합(VTI+EWY)
    - target="ASSET_ID": 특정 자산 비중
    """
    w = policy_compute_weights(policy, x, params, mu_model)
    if target == "equity_total":
        return float(w.loc[EQUITY_ASSETS].sum())
    if target in ASSETS:
        return float(w.loc[target])
    raise ValueError("target must be equity_total or one of ASSETS")

def kernel_shap_explain(policy: str,
                        x_explain: np.ndarray,
                        X_background: np.ndarray,
                        params: PolicyParams,
                        mu_model: MuModel,
                        target: str = "equity_total",
                        nsamples: int = 200,
                        top_k: int = 8):
    """
    단일 샘플 x_explain에 대한 Kernel SHAP 로컬 설명.
    - background는 실제 월 샘플들로 구성(입력 공간을 현실적으로 유지)
    - 출력은 top_k features 요약 리스트
    """
    def f(X):
        out = []
        for i in range(X.shape[0]):
            out.append(policy_target_value(policy, X[i], params, mu_model, target=target))
        return np.array(out, dtype=float)

    explainer = shap.KernelExplainer(f, X_background)
    shap_vals = explainer.shap_values(x_explain.reshape(1, -1), nsamples=nsamples)
    # shap_vals: (1, n_features)
    sv = np.array(shap_vals).reshape(-1)

    fn = feature_names()
    # feature 값도 같이 저장(LLM 요약용)
    fx = x_explain.reshape(-1)
    # 절대값 기준 top_k
    idx = np.argsort(np.abs(sv))[::-1][:top_k]

    top = []
    for j in idx:
        top.append({
            "feature": fn[j],
            "value": float(fx[j]),
            "shap": float(sv[j]),
            "direction": "UP" if sv[j] > 0 else "DOWN"
        })

    # base_value는 KernelExplainer에서 expected_value로 접근 가능(단 케이스에 따라 배열)
    base = explainer.expected_value
    if isinstance(base, (list, np.ndarray)):
        base_value = float(np.array(base).reshape(-1)[0])
    else:
        base_value = float(base)

    return top, base_value

## 월 1개(eom) 기준 최종 사용자 리포트

In [65]:
# =========================
# I) 월 1개(eom) 기준 "최종 사용자 리포트"
# =========================
def opposite_profile(profile: str) -> str:
    return "AGGRESSIVE" if profile == "CONSERVATIVE" else "CONSERVATIVE"

def portfolio_to_table(weights: pd.Series,
                       eps: float = 1e-6,
                       round_decimals: int = 4) -> pd.DataFrame:
    """
    pd.Series(자산->weight)를 사람이 보기 좋은 테이블로 변환
    """
    w = weights.copy()
    w[np.abs(w) < eps] = 0.0        # 거의 0인 값 제거
    w = w / w.sum() if w.sum() > 0 else w  # 안전 재정규화

    df = (
        w.rename("weight")
         .reset_index()
         .rename(columns={"index": "asset"})
    )
    df["weight"] = df["weight"].round(round_decimals)
    df["weight_pct"] = (df["weight"] * 100).round(2)

    df = df.sort_values("weight", ascending=False).reset_index(drop=True)
    return df

def shap_to_table(shap_list: list[dict]) -> pd.DataFrame:
    df = pd.DataFrame(shap_list)

    # feature 분해: 자산 / 변수
    def split_feature(f):
        if "__" in f:
            left, right = f.split("__", 1)
            return left, right
        return f, ""

    df[["entity", "metric"]] = df["feature"].apply(
        lambda x: pd.Series(split_feature(x))
    )

    # 보기 좋게 정렬
    df["abs_shap"] = df["shap"].abs()
    df = df.sort_values("abs_shap", ascending=False)

    return df[[
        "entity", "metric", "value", "shap", "direction"
    ]]

def generate_user_report(engine, eom: pd.Timestamp, user_profile: str,
                         params: PolicyParams, mu_model: MuModel,
                         background_months: int = 60,
                         nsamples: int = 200,
                         top_k: int = 8):
    """
    요구사항 #4:
    - 사용자 성향 포트폴리오 + 국면 + 중요요인(=Kernel SHAP top features)
    - 반대 성향 포트폴리오도 함께 제시
    """
    # 공통 eom 캘린더 확보
    common_eoms = get_common_eoms(engine, min_assets=len(ASSETS))
    common_eoms = pd.to_datetime(common_eoms)

    if eom not in set(common_eoms):
        raise RuntimeError(f"demo_eom {eom.date()} is not in common eom calendar")
    
    # 1) state 로드
    st = load_state(engine, eom)
    regime = st["regime"]

    # 2) background eom 추출(최근 background_months)
    q_bg = """
    select eom from regime_monthly
    where eom < :eom
    order by eom desc
    limit :n
    """
    bg_eoms = [d for d in common_eoms if d < eom]
    bg_eoms = bg_eoms[-background_months:]
    if len(bg_eoms) < 20:
        raise RuntimeError("Not enough background eoms for Kernel SHAP")

    # 3) 사용자 profile 결과
    x_user = state_to_X(st, user_profile)
    policy_user = choose_policy(regime, user_profile)
    w_user = policy_compute_weights(policy_user, x_user, params, mu_model)

    # 4) 반대 profile 결과 (counterfactual)
    opp = opposite_profile(user_profile)
    x_opp = state_to_X(st, opp)
    policy_opp = choose_policy(regime, opp)
    w_opp = policy_compute_weights(policy_opp, x_opp, params, mu_model)

    # 5) SHAP(동일한 방식) - “왜 주식비중합(equity_total)이 이런 값인가”
    # background는 같은 profile로 맞추는 게 보통 더 깔끔함(입력공간 비교가 공정)
    X_bg_user = build_X_matrix(engine, bg_eoms, user_profile)
    top_user, base_user = kernel_shap_explain(policy_user, x_user, X_bg_user, params, mu_model,
                                             target="equity_total", nsamples=nsamples, top_k=top_k)

    X_bg_opp = build_X_matrix(engine, bg_eoms, opp)
    top_opp, base_opp = kernel_shap_explain(policy_opp, x_opp, X_bg_opp, params, mu_model,
                                           target="equity_total", nsamples=nsamples, top_k=top_k)

    portfolio_user_tbl = portfolio_to_table(w_user)
    portfolio_opp_tbl  = portfolio_to_table(w_opp)

    shap_user_tbl = shap_to_table(top_user)
    shap_opp_tbl  = shap_to_table(top_opp)

    return {
        "meta": {
            "eom": str(eom.date()),
            "regime": regime,
            "profile": user_profile,
            "policy": policy_user
        },
        "portfolio_user": portfolio_user_tbl,
        "portfolio_opposite": portfolio_opp_tbl,
        "xai_user": shap_user_tbl,
        "xai_opposite": shap_opp_tbl
    }

## 실행 예시

In [66]:
# =========================
# J) 실행 예시 (regime_monthly까지 존재한다고 가정)
# =========================
def run_demo(engine, demo_eom: str):
    """
    1) ret_wide 로딩 + 전역 corr 추정
    2) mu_model 학습
    3) demo_eom에서 사용자 리포트 생성
    """
    eom = pd.to_datetime(demo_eom)

    ret_wide = load_ret_wide(engine)
    corr = estimate_global_corr(ret_wide, window_months=60)

    mu_model = train_mu_model(engine, ret_wide)

    params = PolicyParams(corr=corr)

    report_cons = generate_user_report(engine, eom, "CONSERVATIVE", params, mu_model,
                                       background_months=60, nsamples=200, top_k=3)
    report_aggr = generate_user_report(engine, eom, "AGGRESSIVE", params, mu_model,
                                       background_months=60, nsamples=200, top_k=3)

    return report_cons, report_aggr

In [67]:
report_cons, report_aggr = run_demo(ENGINE, "2025-12-31")
report_cons

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

{'meta': {'eom': '2025-12-31',
  'regime': 'RISK_ON',
  'profile': 'CONSERVATIVE',
  'policy': 'CAR_RP'},
 'portfolio_user':          asset  weight  weight_pct
 0     CASH_BIL  0.7022       70.22
 1     GOLD_GLD  0.1133       11.33
 2   GLB_EQ_VTI  0.1123       11.23
 3  LT_BOND_TLT  0.0590        5.90
 4    KR_EQ_EWY  0.0132        1.32,
 'portfolio_opposite':          asset  weight  weight_pct
 0   GLB_EQ_VTI  0.6783       67.83
 1     GOLD_GLD  0.2840       28.40
 2    KR_EQ_EWY  0.0377        3.77
 3     CASH_BIL  0.0000        0.00
 4  LT_BOND_TLT  0.0000        0.00,
 'xai_user':        entity  metric     value      shap direction
 0    CASH_BIL  vol_3m  0.002064  0.077394        UP
 1  GLB_EQ_VTI  vol_3m  0.013198  0.032614        UP
 2   KR_EQ_EWY  vol_3m  0.137111 -0.017892      DOWN,
 'xai_opposite':         entity  metric     value      shap direction
 0   GLB_EQ_VTI  ret_3m  0.021635  0.110674        UP
 1    KR_EQ_EWY  ret_1m  0.069880 -0.089066      DOWN
 2  LT_BOND_TLT   dd_6m -0.046256  0.069821        UP}

In [68]:
report_cons['portfolio_user']

         asset  weight  weight_pct
0     CASH_BIL  0.7022       70.22
1     GOLD_GLD  0.1133       11.33
2   GLB_EQ_VTI  0.1123       11.23
3  LT_BOND_TLT  0.0590        5.90
4    KR_EQ_EWY  0.0132        1.32

In [69]:
report_cons['xai_user']

       entity  metric     value      shap direction
0    CASH_BIL  vol_3m  0.002064  0.077394        UP
1  GLB_EQ_VTI  vol_3m  0.013198  0.032614        UP
2   KR_EQ_EWY  vol_3m  0.137111 -0.017892      DOWN

In [70]:
report_cons['portfolio_opposite']

         asset  weight  weight_pct
0   GLB_EQ_VTI  0.6783       67.83
1     GOLD_GLD  0.2840       28.40
2    KR_EQ_EWY  0.0377        3.77
3     CASH_BIL  0.0000        0.00
4  LT_BOND_TLT  0.0000        0.00

In [71]:
report_cons['xai_opposite']

        entity  metric     value      shap direction
0   GLB_EQ_VTI  ret_3m  0.021635  0.110674        UP
1    KR_EQ_EWY  ret_1m  0.069880 -0.089066      DOWN
2  LT_BOND_TLT   dd_6m -0.046256  0.069821        UP